name: colcon

on:
  pull_request:
    paths-ignore:
      - "README.md"

jobs:
  build:
    name: "${{ matrix.distribution }} (${{ matrix.ros }})"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - distribution: ubuntu
            version: 22.04
            ros: humble

          - distribution: ubuntu
            version: 24.04
            ros: jazzy

          - distribution: almalinux
            version: 8
            ros: humble

          - distribution: almalinux
            version: 9
            ros: jazzy

    continue-on-error: ${{ matrix.ros == 'rolling' }}

    container:
      image: ${{ matrix.distribution }}:${{ matrix.version }}
      env:
        DEBIAN_FRONTEND: noninteractive
        PIP_BREAK_SYSTEM_PACKAGES: 1

    steps:
      - name: fetch source
        uses: actions/checkout@v4

      - name: install ROS 2
        uses: ros-tooling/setup-ros@v0.7

      - name: colcon lint dependencies
        run: |
          # apt install -y apt-rdepends ros-${{ matrix.ros }}-launch-ros
          pip install lark
          pip install colcon-lint

      - name: build and test
        uses: ros-tooling/action-ros-ci@v0.3
        id: action_ros_ci
        with:
          package-name: camera_ros
          target-ros2-distro: ${{ matrix.ros }}
          colcon-defaults: |
            {
              "build": {
                "mixin": ["asan-gcc", "tsan", "coverage-gcc", "memcheck"]
              }
            }
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/5d51dff38097e8c2bf46d7a5b804e65935aa7f47/index.yaml

      - name: colcon lint
        working-directory: ${{ steps.action_ros_ci.outputs.ros-workspace-directory-name }}
        run: |
          colcon lint
